### ISSUE TITLE
usb device status

### ISSUE THREAD

**Issue by loomis** [nuvlabox/agent#10]
Obtaining the USB device status currently takes an extremely long time compared to the refresh interval of the NuvlaBox heartbeats. This is causing false alarms concerning the status of the NuvlaBox. 

The cause of this problem is the amount of time it takes to run `lsof` from within a container. The timings for the command:

```
time for i in {1..10}; do lsof /dev/bus/usb/001/002; done
```

are shown in the following table.

| test | time (s) |
| --- | --- |
| bare metal | 0.309 |
| ubuntu 18.04 container (non-priv.) | 12.474 |
| ubuntu 18.04 container (priv.) | 9.084 | 

While the excessive timing of `lsof` can be investigated, it would be useful to update the heartbeat information from the device information separately to ensure that the heartbeat information is sent at a reliable frequency. 

In addition to the timing issue, there is a problem with the deployment of the agent container.  This is done within a non-privileged container, so the device files are **not** available within the container.  Consequently, `lsof` always reports an error and the agent interprets this as the device being free. Unless the agent is deployed in privileged mode, it will **never** report a device as being busy.

**Comment by loomis** [comment]
The behavior is the same on a RPi as well as a standard Exoscale VM; this is not device related.

**Comment by cjdcordeiro** [comment]
## investigation

The tardiness of the `lsof` within a Docker container is most likely related with the way the host filesystem is mounted inside the container. This goes deep into the Docker implementation of the storage driver, but what is observed is that during `lsof`, the file `/proc/filesystems` is opened, read and closed. The closing operation however, inside the container, takes hundreds of thousands of attempts before succeeding: `-1 EBADF (Bad file descriptor)`.

## solution

There's no clear solution on how to make this run faster. A possible solution would be to simply replace `lsof` by another command or script which simply looks at the device ID and checks whether there is a process making use of it. 

However, the best solution is actually to simply remove this line. This is because `lsof` will not be able to infer whether a device is being used by another container, even if running on privileged mode. Such information can only be obtainer from the respective container...so it doesn't make sense to have this in the `agent` as a overview call for all devices in the host.

## next steps

create the iot-manager (https://github.com/nuvlabox/iot-manager/issues/1), which will take care of discovering, categorizing and managing all peripherals. Everything related with peripherals, which might disrupt the agent's hearbeat, will be moved into this new component
